spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher




jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "qiaqiabkj" #密钥
  expireTime: 200000 #有效时间



# 不建议在这里填写数据库JDBC URL和用户名密码：
# 1. 出于安全考虑。
# 2. 每个人的数据库连接不一定一样，所以在此填写总会被改动，不利于git协作。
# 建议的做法是从application-dev.example.yml创建一个文件application-dev.yml，在该文件中进行设置。
#spring:
#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name: