name: Build and push Docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build and push Docker image
      env:
        "docker.registry.url": ${{  secrets.DOCKER_REGISTRY_URL  }}
        "docker.registry.username": ${{  secrets.DOCKER_REGISTRY_USERNAME  }}
        "docker.registry.password": ${{  secrets.DOCKER_REGISTRY_PASSWORD  }}
        "docker.image.name.backend": ${{  secrets.DOCKER_IMAGE_NAME_BACKEND  }}
      run: ./gradlew :dockerPushImage
      
