name: Build and push Docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: DEBUG
      run: pwd && ls -l
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Setup Docker
      uses: docker/build-push-action@v2.10.0
    - name: Build abd push Docker image
      env:
        DOCKER_REGISTRY_URL: ${{  secrets.DOCKER_REGISTRY_URL  }}
        DOCKER_REGISTRY_USERNAME: ${{  secrets.DOCKER_REGISTRY_USERNAME  }}
        DOCKER_REGISTRY_PASSWORD: ${{  secrets.DOCKER_REGISTRY_PASSWORD  }}
        DOCKER_IMAGE_NAME_BACKEND: ${{  secrets.DOCKER_IMAGE_NAME_BACKEND  }}
      run: ./gradlew :dockerPushImage
      
